MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 10
  DUAL_HEAD: TRUE
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 10
  DUAL_HEAD: TRUE
DATASET_SOURCE:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_singapore",)
  TEST: ("test_singapore",)
  NuScenesLidarSegSCN:
    preprocess_dir: "/data/AmitRoyChowdhury/xmuda/nuscenes_lidarseg/preprocess"
    nuscenes_dir: "/data/AmitRoyChowdhury/nuscenes"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "/data/AmitRoyChowdhury/xmuda/SemanticKITTI/preprocess"
    semantic_kitti_dir: "/data/AmitRoyChowdhury/SemanticKITTI"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.27673237, 2.28281817, 4.07063844, 3.19973815, 1., 0.,         2.09485643, 1.53682289, 1.53727826, 1.97895212]
VAL:
  BATCH_SIZE: 8 
  PERIOD: 5000
OUTPUT_DIR: "/data/AmitRoyChowdhury/xmuda/pselab/@"
#OUTPUT_DIR: "eval_result/@"
