MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_day",)
  TEST: ("test_day",)
  NuScenesSCN:
    preprocess_dir: "/data/AmitRoyChowdhury/xmuda/nuscenes/preprocess"
    nuscenes_dir: "/data/AmitRoyChowdhury/nuscenes"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_night",)
  VAL: ("val_night",)
  TEST: ("test_night",)
  NuScenesSCN:
    preprocess_dir: "/data/AmitRoyChowdhury/xmuda/nuscenes/preprocess"
    nuscenes_dir: "/data/AmitRoyChowdhury/nuscenes"  # only front cam images are needed
    pselab_paths: "/home/eegrad/csimons/Projects/xmuda/refined_pselab/nuscenes/day_night/unimodal.npz"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.00001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
#  CLASS_WEIGHTS: [2.68678412, 4.36182969, 5.47896839, 3.89026883, 1.] # Calculated on source
  CLASS_WEIGHTS: [3.03536195, 4.31818534, 5.33373101, 4.35830821, 1.] # Estimated with pseudo labels
  XMUDA:
    lambda_ent: 0.
    lambda_div: 0.
    lambda_xm_trg: 0.1
    lambda_pl: 1.0
    ckpt_2d: '/home/eegrad/csimons/Projects/xmuda/output/76015/nuscenes/day_night/baseline/model_2d_100000.pth'
    ckpt_3d: '/home/eegrad/csimons/Projects/xmuda/output/76015/nuscenes/day_night/baseline/model_3d_100000.pth'
VAL:
  BATCH_SIZE: 32
  PERIOD: 5000
OUTPUT_DIR: "eval_result/@"
